  version: 2.1
  jobs:
    build:
      docker: 
        - image: rcombs77/cci-clay-docker:0.0.1 # the primary container, where your job's commands are run
      steps:
        - checkout # check out the code in the project directory
        - run: npm run lint-css # run the `echo` command
        
