  version: 2.1
  jobs:
    build:
      docker: 
        - image: circleci/ruby:2.4-node
      steps:
        - checkout # check out the code in the project directory
        - run: cd app && npm install 
        - run: cd app && npm run lint-css        
